apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170170149
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/bkgvdixl-tenant/test-app-170170149/java-quarkus-170170149@sha256:833a7eada1436b3ad501c461c14f7988707a60b6ae5756749556fbc27abd849a
        name: my-java-quarkus
        resources: {}
status: {}
